services:
  pizquito-strapi:
    container_name: pizquito-strapi
    build: .
    image: pizquito-strapi:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/app/package.json
      - ./package-lock.json:/opt/app/package-lock.json
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '${PORTX}:1337'
    networks:
      - pizquito-strapi
    depends_on:
      - pizquito-strapi-db

  pizquito-strapi-db:
    container_name: pizquito-strapi-db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file:
      - .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pizquito-strapi:/var/lib/postgresql/data/ #using a volume
#      - ./postgresql_data:/var/lib/postgresql/data/ # if you want to use a bind folder

#    ports:
#      - '5432:5432'
    networks:
      - pizquito-strapi


volumes:
  pizquito-strapi:

networks:
  pizquito-strapi:
    name: Pizquito-strapi
    driver: bridge
