name: Deploy

on:
  push:
    branches:
      - migration

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH key to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -p 2121 51.222.42.143 >> ~/.ssh/known_hosts

    - name: Copy files to VPS
      run: scp -P 2121 -r ./* administrator@51.222.42.143:/home/administrator/test/pizquito-backend-strapi

    - name: Deploy with Docker Compose
      run: |
        ssh administrator@51.222.42.143 -p 2121 << 'EOF'
          cd /home/administrator/test/pizquito-backend-strapi
          docker compose down
          docker compose up -d
        EOF
